return {
	{
		"nvim-treesitter/nvim-treesitter",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"c",
					"lua",
					"markdown",
					"bash",
					"cpp",
					"dart",
					"asm",
					"arduino",
					"angular",
					"css",
					"gdscript",
					"go",
					"javascript",
					"typescript",
					"graphql",
					"json",
					"nim",
					"nasm",
					"nginx",
					"perl",
					"php",
					"prisma",
					"python",
					"ruby",
					"rust",
					"scss",
					"sql",
					"svelte",
					"tsx",
					"vue",
					"xml",
					"yaml",
					"zig",
					"cmake",
					"html",
				},
				auto_install = true,
				highlight = {
					enable = true,
				},
			})
		end,
	},
}
